version: '3.8'
services:
  app:
    image: steevi83/qrscanner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/qcode_spring
      SPRING_DATASOURCE_USERNAME: qcode_app_user
      SPRING_DATASOURCE_PASSWORD: p4ssw0rd
    depends_on:
      - db

  db:
    image: mariadb:11.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: malagasy
      MARIADB_DATABASE: qcode_spring
      MARIADB_USER: qcode_app_user
      MARIADB_PASSWORD: p4ssw0rd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
